### ISSUE TITLE
Rebase on GNOME Ease.

### ISSUE THREAD

**Issue by desiderantes** [Philip-Scott/Spice-up#1]
Ease is an abandoned GNOME project, written in Vala, and in a semi-working state, so maybe you could do a Pantheon Photos with it.

**Comment by Philip-Scott** [comment]
TBH, i'm doing this more for the challenge for me. That mockup was the main reason i started learning Vala. I've been wanting to code it ever sense, and now i finally have the knowledge to do so :)

**Comment by desiderantes** [comment]
Oh Ok, have fun! I'll keep an eye on this because a good competition is needed for Powerpoint. Maybe Prezi but with good performance? Let's see how this turns out 😃
