### ISSUE TITLE
Search fonts

### ISSUE THREAD

**Issue by Philip-Scott** [Philip-Scott/Spice-up#107]

**Comment by aleksandar-stefanovic** [comment]
How should this be done design-wise, are there any design cues?
We could do it like we did with Code (https://github.com/elementary/code/commit/cefbdb61bcd21c4b0cd66838dda9d09753580605):
![screenshot from 2018-01-12 00 12 40](https://user-images.githubusercontent.com/6058082/34852111-558dc530-f72d-11e7-89a4-0eb77140aeff.png)

**Comment by Philip-Scott** [comment]
That's actually a great idea about how to do it! I quite like the style except for the "checkbox"  :) 

I think that the way to do it would be to add a `bool searchable` property to the EntryCombo widget on Spice-Up, and if that's true it shows the entry for searching. because it would really only make sense on Fonts and the background texture on the main canvas, and not on the one for font size

**Comment by aleksandar-stefanovic** [comment]
I meant just adding the search bar to the popover, we shouldn't use checkboxes in this case.

Okay, I will try to implement adding a search bar to the widget, consider that I'm working on this.

**Comment by Philip-Scott** [comment]
Sweet! You're awesome dude! Thanks for your help 😄
