### ISSUE TITLE
Black portion appears under the text with fcitx

### ISSUE THREAD

**Issue by ryonakano** [Philip-Scott/Spice-up#110]
When I added textbox, black portion appeared under the text like this screenshot and couldn't remove.
This also appears even in presentation mode.

Loki 0.4.1, Spice-Up 0.4.6
![screenshot from 2017-05-18 20-44-57](https://cloud.githubusercontent.com/assets/26003928/26201060/1410d368-3c0c-11e7-93b1-7cf2e44cdfee.png)

**Comment by Philip-Scott** [comment]
I can't seem to confirm it :/ Does it happen on every font?

**Comment by ryonakano** [comment]
Yes, it still appears even I changed font.
Also, I reinstalled elementary OS and Spice-up after posting this issue, but the situation didn't changed.
![screenshot from 2017-05-22 21-07-25](https://cloud.githubusercontent.com/assets/26003928/26308203/2db458ba-3f33-11e7-83bc-3702662cf0ab.png)

**Comment by ryonakano** [comment]
Yes, it still appears even I changed font.
Also, I reinstalled elementary OS and Spice-up after posting this issue, but the situation didn't changed.
![screenshot from 2017-05-22 21-15-03](https://cloud.githubusercontent.com/assets/26003928/26308389/fd70676a-3f33-11e7-8d59-ac618880732e.png)

**Comment by ryonakano** [comment]
Now I found the cause of this issue.
This is because of the input-method, fcitx.
When fcitx is running, this issue is happen.
If not, this issue isn't happen.
![screenshot from 2017-05-22 23-06-00](https://cloud.githubusercontent.com/assets/26003928/26312907/29078952-3f44-11e7-9048-0ff5f5f8cfd6.png)
This screenshot is when I stopped running fcitx.

**Comment by ryonakano** [comment]
However, I can't type Japanese when the fcitx isn't running:(
This issue is serious...

**Comment by Philip-Scott** [comment]
At least now we know what the reason is :) fcitx might be adding it's own CSS to textboxes. I'll check it out and see if there's anything i can do

**Comment by ryonakano** [comment]
Thank you!

**Comment by Philip-Scott** [comment]
@ryonakano are you using any skins?

**Comment by ryonakano** [comment]
fcitx's skins?

**Comment by Philip-Scott** [comment]
No idea :P I just installed fcitx and it's also not causing the textbox to go black.... So it might be a configuration you have

**Comment by ryonakano** [comment]
I see... Please let me check my configuration.

**Comment by ryonakano** [comment]
Umm, I don't change my fcitx configuration so much, though...
I changed only host-key and "Fcitx XIM Frontend" setting.

**Comment by ryonakano** [comment]
In the latest version 0.5.5, the black portion doesn't appear in presentation mode.
But it still appears when I clicked in  the textbox:
![screenshot from 2017-05-26 20-10-44](https://cloud.githubusercontent.com/assets/26003928/26492657/32d30808-4250-11e7-9ae0-27bc9c7f6634.png)

**Comment by Philip-Scott** [comment]
Yeah, i made a change where the editor is not the same as the viewing text. :) This might be a problem with fcitx though and not something i can fix from within my app (I am already removing the background on the textbox as you can see when you disable fcitx) since I think that the program is injecting it's own styles.
 
But since it won't be bothering you while presenting, i think i'm going to close it if that's good with you :) At least you will be able to present without a problem

**Comment by ryonakano** [comment]
I understand it.
Thank you for your quick fixing!
