### ISSUE TITLE
The new update can't read content of old presentation files

### ISSUE THREAD

**Issue by ehrtz** [Philip-Scott/Spice-up#119]
I don't know if it can't read the content of the file but when i open my previously created presentation (without spice extension) no slide has been displayed. its like it just create new one and save as with spice extension (filename became filename.spice).
![spice](https://cloud.githubusercontent.com/assets/25916626/26329036/f2b273b0-3f77-11e7-9750-fa3c38c263fc.png)

**Comment by Philip-Scott** [comment]
I'll check that out tonight after work. I think i know what went wrong. In the meantime, if you add .spice you should be able to open i

**Comment by Philip-Scott** [comment]
Yup, sorry about that. I did a silly thing and added the .spice to all files instead of just trying to create new ones (Even the pictures...) You'll be able to get an update from AppCenter today in a few minutes :)

**Comment by ehrtz** [comment]
yes adding the spice extension will allow me to open my presentation. 

BTW the icon of the App is also broken (missing).

**Comment by Philip-Scott** [comment]
Hopefully the update fixed those problems :)
