### ISSUE TITLE
Saved file format

### ISSUE THREAD

**Issue by Clifspeare** [Philip-Scott/Spice-up#120]
Presentations are saved as text files, which can be a little inconvenient as Spice-up can't be set as the default application to open them in file managers without messing up other text files.

**Comment by Philip-Scott** [comment]
Did you install the app from AppCenter? the .spice files should be open-able by the app (The icon will show as the text file.... still haven't figured that one out)

**Comment by SkyzohKey** [comment]
@Philip-Scott this may help you https://help.ubuntu.com/community/AddingMimeTypes

**Comment by Philip-Scott** [comment]
@SkyzohKey Hey thanks! :) That was actually what i needed! Now the filles will have an icon (All i need now is to make a better icon!)
