### ISSUE TITLE
Add shape, text-box and image options

### ISSUE THREAD

**Issue by aggalex** [Philip-Scott/Spice-up#130]
The shape options in the app are too few. You can only create a rectangle and nothing else. You can't also edit the contents of the circle. These are my suggestions:

- I suggest a small dropdown with different shapes. You could start with the basics like circles/ovals, lines, etc.

- Grouping is a must when we are talking about graphics. You should add that too. You should add a n option to group/ungroup selected items, like text boxes, shapes and images.

- Also, I suggest adding shape fill and outline options. Just a horizontal/vertical fill gradient isn't enough. You need to add image fill, fill and outline patterns and textures (like the background), and gradient angle options (how many degrees will the gradient tilt). You also need to add opacity options.

- Moreover, I suggest adding image filters and effects. For the filters, you could add instagram-like filters and vignette, contrast, brightness, tilt, blur etc. options. For the effects, I think shaddows, glows, blur and 3d-like edges (like elementary has in it's windows, icons, etc.) would suffice.

**Comment by Philip-Scott** [comment]
Hey, yes some of this things will be coming in the next few versions. Some others can't happen due to technology limitations. Also, please only make one report per issue, as it makes tracking features/bugs easier 

Marking as invalid and closing due to that :)
