### ISSUE TITLE
It should be possible to set color1 and color2 by one click

### ISSUE THREAD

**Issue by artemanufrij** [Philip-Scott/Spice-up#135]
If you don't need a gradient, you must choose same color for both _colors_.

I think an option like `shift` + `click` on a color for selection a color for both _colors_ would be very helpful.

**Comment by Philip-Scott** [comment]
Yeah, that could work but i'd also like to do it in such a way where it's not hidden behind a keyboard shortcut. :)

**Comment by Philip-Scott** [comment]
Fixed on e010e05347a69ec53e40d5086790593818f69d3c.

In the new versions, you can change both colors by pressing on the preview. Both colors will change by default unless you select either color1 or color2 :)
