### ISSUE TITLE
Show indication when end of presentation is reached

### ISSUE THREAD

**Issue by yeboahnanaosei** [Philip-Scott/Spice-up#144]
Currently, the way spice-up exits from presentation mode or view is a bit too abrupt. It will be nice to show a blank screen which says "End of presentaion" and then exit the presentation when the user clicks or presses the arrow key one more time.

**Comment by cassidyjames** [comment]
Even without text, a black "slide" after the presentation contents isn't a terrible idea. I usually just add one in manually anyway.

**Comment by Philip-Scott** [comment]
Fixed on #175 :)

**Comment by Philip-Scott** [comment]
Added a black slide when the end is reached
