### ISSUE TITLE
Deleting all content on presentation can crash

### ISSUE THREAD

**Issue by cassidyjames** [Philip-Scott/Spice-up#148]
It looks like if you delete all slides on a presentation, then toggle between the Welcome Screen and now-blank presentation a few times, you can get Spice-up to crash.

**Comment by Philip-Scott** [comment]
I found the fix for the crash, but i'm thinking about just deleting the presentation if it didn't have any slides when you saved it. Because:

1. Why would you want to keep an empty presentation
2. It will make it so it also doesn't appear on the presentations browser

**Comment by Philip-Scott** [comment]
for now, crash fixed f63e37e

**Comment by cassidyjames** [comment]
@Philip-Scott yeah if there's no content on a presentation **and** the user navigates away (i.e. to the Welcome Screen or perhaps closes the app), I think you can safely delete it.
