### ISSUE TITLE
Make SlideList a ListBox 

### ISSUE THREAD

**Issue by aberba** [Philip-Scott/Spice-up#15]
When adding a new slide, you replace the  `+` button every time which seem in-efficient. Why not just append the new slide and just put focus on the newly added slide (for user to edit)? (If I understood the code well ::smile::)

**Comment by Philip-Scott** [comment]
Yeah, the whole code for that bar will pretty much be gone in the future :) It's mostly just the bare bones until i can figure out what i will do with the previews. Once that's done, it will use a Gtk.ListBox and the slides will be it's own class

First i need to solve the Preview caching problem.... I'm thinking of using a "zipped" file for the save format, and in there we can store .png of the previews (Along with images so they don't have to rely on always being on the dist) But right now I have no idea on how i could use Zipped file as a "Folder" to access files without having to unzip everything into /tmp first :(

**Comment by aberba** [comment]
You could use your own custom .~/tmp directory with some form of hashing.

**Comment by Philip-Scott** [comment]
Nah, what i did to solve the preview problem was to just place the Canvas widget on the slides, but making it not editable :)

**Comment by aberba** [comment]
Was taking about saving unzipping to a custom tmp. 

About the preview part, how was it done in the GTK+ Presenation app a guy sent you to check on? Its screenshot seems to have preview working.
