### ISSUE TITLE
How to save file on version 1.0.0??

### ISSUE THREAD

**Issue by WebShapedBiz** [Philip-Scott/Spice-up#150]
As I remember there is a dialog to specify new file when starting a new presentation. Now I don't have it and I just don't see how to save my work.

**Comment by Philip-Scott** [comment]
@WebShapedBiz Hey! Files are saved automatically to a presentations folder inside of your documents folder. These are shown on the Welcome screen when you come back, and you can open the file location my right clicking it and pressing the Folder button opens the location

**Comment by WebShapedBiz** [comment]
Nice, thank you for clarification. Didn't expect to see such drastic change
of file handling paradigm, kudos.

Best regards,

Sinisa Perovic
WebShaped.biz

Web: http://www.webshaped.biz
E-Mail: sinisaperovic@webshaped.biz
SkypeID: sinisaperovic
Telegram: @sinisaperovic

2017-09-14 19:54 GMT+02:00 Felipe Escoto <notifications@github.com>:
