### ISSUE TITLE
Install as com.github.philip-scott.spice-up

### ISSUE THREAD

**Issue by NicoHood** [Philip-Scott/Spice-up#151]
Hi,
I am writing a PKGBUILD for archlinux. I dont know why, but the final app inside /usr/bin is called `com.github.philip-scott.spice-up` instead of just `spice-up`. I am using version 1.0.0, I guess that is a bug?

**Comment by Philip-Scott** [comment]
Nop, it's not a bug :) app names should also use the domain name as well to prevent collisions.

if there is anything else you would need to change let me know!

**Comment by NicoHood** [comment]
But this makes it very hard to run from the commandline. Noone would think of this name. Collisions should be detected by your package manager, and also it is very unlikely that someone else will name the app with the same name.

**Comment by Philip-Scott** [comment]
Well 99% of the time you will run it by clicking on the button :wink: But this is just the new way of doing package names, and all the other elementary apps are following this naming convention

You can always make a symlink from the executable to `/usr/bin/spice-up`

**Comment by Philip-Scott** [comment]
See https://medium.com/elementaryos/cleaning-up-app-codenames-ef9fc637ddef for more details and the reasoning behind :)

**Comment by NicoHood** [comment]
Alright, I've added a symlink to the package.

**Comment by Philip-Scott** [comment]
Perfect, thank you :) And i'm glad that i got Gtk3.22+ support working already! :sweat_smile:

**Comment by NicoHood** [comment]
BTW the AUR link for the googlers:


Offtopic:
As you might have seen I've posted #152 about GPG signatures. It would be nice if you can gpg sign your software, but also help spreading the word to the elementary team. I've seen you've been working with them multiple times, so you might have a better chance to realize it.

I've already opened multiple issues on several EOS projects. In order to bring the pantheon desktop to other distributions (in this case ArchLinux) we need release tags and signed sources in order to distribute the software securely. Some of the issues I've opened are below:
* https://github.com/elementary/cerbere/issues/13
* https://github.com/elementary/gala/issues/25

Thanks :)

**Comment by Philip-Scott** [comment]
You should speak directly to [Cody Garver](https://github.com/codygarver), he's the one in charge of making the releases and such for the elementary projects :) That way you can explain it to him directly in case he has any questions

**Comment by NicoHood** [comment]
Thanks. I've emailed him too. What about you, could you please GPG sign your releases? I am willing to publish them into the official repos, once they are popular enough :)

**Comment by Philip-Scott** [comment]
Yeah, of course. I'll sign the next one when it's ready :) I'll ping you when i'm about to do it so that you can walk me though it.
