### ISSUE TITLE
Granite version is incorrect on readme

### ISSUE THREAD

**Issue by xisberto** [Philip-Scott/Spice-up#153]
In the build instructions, granite is listed as a dependency in version >=0.3

But during make, it gets "The type name `Granite.Widgets.Toast' could not be found", as this class was introduced on granite 0.4.1.

**Comment by Philip-Scott** [comment]
Updated, thank you for bringing it up! 

If you want to install it on your system, try to compile https://github.com/elementary/granite/ manually, or install it from the elementary daily PPA :)
