### ISSUE TITLE
Spice-Up tries to create a (null) directory (when snapped)

### ISSUE THREAD

**Issue by popey** [Philip-Scott/Spice-up#155]
After seeing [this thread](https://www.reddit.com/r/Ubuntu/comments/70ltu9/spiceup_is_a_native_presentations_app_built_for/) I discovered Spice-up. Nice application! 

I thought I'd take a look at making a snap of the application, which I did over the weekend and it launches, but when I try and create a new presentation it does nothing when I double click the template. I see this in the console where I launched the app. Any idea what the (null) is supposed to be?

```
[INFO 12:56:42.436262] Application.vala:153: Spice-Up version: 0.8
[INFO 12:56:42.436294] Application.vala:155: Kernel version: 4.10.0-33-generic
[FATAL 12:56:45.463065] file /root/build_spice-up/parts/spice-up/src/src/Services/FileManager.vala: line 100: uncaught error: Failed to create file '/home/alan/(null)/Untitled Presentation 1.spice.0DIH6Y': No such file or directory (g-file-error-quark, 4)
[FATAL 12:56:45.673584] file /root/build_spice-up/parts/spice-up/src/src/Services/FileManager.vala: line 100: uncaught error: Failed to create file '/home/alan/(null)/Untitled Presentation 1.spice.01PD6Y': No such file or directory (g-file-error-quark, 4)
```

**Comment by Philip-Scott** [comment]
The app tried to grab the Documents folder on your environment variables, Since the snap probably doesn't have a Doc dir, it's trying to open a Null folder...

You should probably allow your snap to access the user's docs :) I'll try to make it so that if it's null, it tries to open a file in the home folder instead

**Comment by popey** [comment]
Thanks for the prompt reply! What environment variable is it specifically looking for? I can set that.

**Comment by Philip-Scott** [comment]
It looks like it's not a normal env variable, but one of the XDG special user directories, this is the Vala function i use to grab that:
https://valadoc.org/glib-2.0/GLib.Environment.get_user_special_dir.html

More info about them: https://wiki.archlinux.org/index.php/XDG_user_directories

**Comment by popey** [comment]
Looks like this is a problem with the desktop helper script I am using to launch the application. I started a [thread](https://forum.snapcraft.io/t/setting-xdg-data-dirs-in-desktop-snaps/2173) to let our developers know about it. Thanks!

**Comment by Philip-Scott** [comment]
That's great, thanks for letting me know! I'll still try to catch this null and do better error handling :)
