### ISSUE TITLE
Provide AppImage using Travis CI autobuild

### ISSUE THREAD

**Issue by Symbian9** [Philip-Scott/Spice-up#156]
* [ ] https://github.com/Philip-Scott/Spice-up/blob/master/.travis.yml
* [ ] https://github.com/Philip-Scott/Spice-up/blob/autobuild/Spice-up_autobuild-x86_64.AppImage

FAQ
* https://github.com/AppImage/
  * https://github.com/mkulesh/microMathematics/tree/master/autobuild
  * https://github.com/probonopd/uploadtool
* https://docs.travis-ci.com/user/customizing-the-build

**Comment by Philip-Scott** [comment]
See https://github.com/Philip-Scott/wallpaperize/issues/16#issuecomment-360959050 for the full read. But Spice-Up is already available as a flatpak, so i don't think theres a need to make yet another package for this app.

Plus, i don't have the time or resources to keep testing and developing on more distributions
