### ISSUE TITLE
Can't install Spice-up on Ubuntu 17.10

### ISSUE THREAD

**Issue by larkvirtual** [Philip-Scott/Spice-up#157]
1. install ubuntu 17.10 amd64
2. `sudo apt-get update && sudo apt-get dist-upgrade`
3. `sudo add-apt-repository ppa:philip.scott/spice-up-daily`
`sudo apt-get update`
`sudo apt-get install com.github.philip-scott.spice-up`
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 com.github.philip-scott.spice-up : Depends: libgranite3 (>= 0.4.1+r1074+really1068+pkg87~daily~ubuntu17.10.1) but it is not installable
E: Unable to correct problems, you have held broken packages.

4. `cat /etc/os-release`
NAME="Ubuntu"
VERSION="17.10 (Artful Aardvark)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu Artful Aardvark (development branch)"
VERSION_ID="17.10"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=artful
UBUNTU_CODENAME=artful

**Comment by Philip-Scott** [comment]
Try adding the elementary daily PPA :)

**Comment by larkvirtual** [comment]
Please tell me a commands to execute?

**Comment by Philip-Scott** [comment]
see https://launchpad.net/~elementary-os/+archive/ubuntu/daily

**Comment by larkvirtual** [comment]
Thanks! At least now Spice-up installed.add to the installation documentation.
