### ISSUE TITLE
spice-up from flathub not allowing me to select presentation 

### ISSUE THREAD

**Issue by sramkrishna** [Philip-Scott/Spice-up#166]
Hey!  I am running the flatpak version of Spice-up which I got from flathub.  I was hoping to use it for a presentation at GNOME Asia.  Unfortunatley, when selecting a new presentation, I can click on the various kinds of presentation but I can't go forward.

**Comment by Philip-Scott** [comment]
Hey! Are you getting any error messages on your console?

**Comment by sramkrishna** [comment]
Here is the error:
(Spice-Up:3): Gtk-WARNING **: Theme parsing error: stylesheet.css:81:18: The :insensitive pseudo-class is deprecated. Use :disabled instead.
[FATAL 12:04:28.428795] file /run/build/spiceup/src/Services/FileManager.vala: line 100: uncaught error: Failed to create file “/home/sri/Downloads/(null)/Untitled Presentation 1.spice.KKC07Y”: No such file or directory (g-file-error-quark, 4)


I suspect that it is not allowing you to create a file in the home directory.  In the flatpak manifest you will need to give access to the home directory I think.

Also, probably want to create it in Documents/Presentations if you want to create such a thing.

**Comment by Philip-Scott** [comment]
Interesting :sweat: 
Just for science, what happens if you create a folder called `(null)` in your Downloads folder? 

And could you give it read-write-execute permissions to it if it also doesn't work?

**Comment by sramkrishna** [comment]
Oops.. sorry, I"ll see if I can do that - yes, it works now. :)

**Comment by Philip-Scott** [comment]
Ok, has been "fixed" on my end :) Hopefully https://github.com/Philip-Scott/Spice-up/commit/819930c2ebbca83cea9034425d6542491d9d9eec is a good fallback
