### ISSUE TITLE
Speaker notes

### ISSUE THREAD

**Issue by sramkrishna** [Philip-Scott/Spice-up#167]
I haven't ran the program yet for obvious reasons.. :-)  But I didn't see it in the list of features, does Spice-Up have speaker notes view?

**Comment by Philip-Scott** [comment]
It's definitely on the TODO list, but currently depends on #90 :) 

Just for a timeline: 

- Next release will be out next week with a bunch of optimizations
- The following release will allow you to open files on any computer, even without the app installed
- Presentation mode and transitions

**Comment by sramkrishna** [comment]
That's great! :)  Thank you for the work!
