### ISSUE TITLE
Reverse cursor

### ISSUE THREAD

**Issue by yotamN** [Philip-Scott/Spice-up#171]
After I edit text, my cursor looks weird:
![screenshot from 2017-11-01 15-04-25](https://user-images.githubusercontent.com/5249239/32276078-62cfb8f6-bf16-11e7-9fa9-83c6f15fce71.png)

This is how it should look:
![screenshot from 2017-11-01 15-04-43](https://user-images.githubusercontent.com/5249239/32276091-7175fadc-bf16-11e7-8346-cd8c1e808051.png)

I'm on Solus

**Comment by Philip-Scott** [comment]
Now it's for 100% sure it's using the default cursor. If this does not work file the issue with Solus 

https://github.com/Philip-Scott/Spice-up/commit/77b1b8718a3046359d8ba438d7f9b992a8d0f78a#diff-9ed8062063ce0a1fbb3eff654dd4a8fcL245
