### ISSUE TITLE
Embed code view

### ISSUE THREAD

**Issue by cassidyjames** [Philip-Scott/Spice-up#174]
My coworker @bencates is giving a presentation at a code conference soon, and was wondering if Spice-Up had embedded code support. I.e. a syntax-highlighted box where he could drop text in for some simple code demos.

In my mind, this would drop a GTKSourceView onto the canvas, and the options in the toolbar would be language, syntax highlighting theme, and font size. If that's even technically possible. :stuck_out_tongue:

**Comment by Philip-Scott** [comment]
I'm going to close this as you can now just Ctrl+V images straight into Spice-Up, so you can just take a screenshot and drop it in the presentation without saving a file
