### ISSUE TITLE
Default open file dialog does not list ".spice" files

### ISSUE THREAD

**Issue by rugk** [Philip-Scott/Spice-up#177]
The default file dialog does not list the ".spice" files. I have to select "All files" instead of "Presentations" (at the bottom right) in order to be able to select the correct file.

installed from Flathub
GNOME v3.26
Fedora 27

**Comment by Philip-Scott** [comment]
as with #178, the flathub is not registering the mime of spice-up.

You should files those issues here :) https://github.com/flathub/com.github.philip_scott.spice-up

Marking this as a duplicate of #178

**Comment by rugk** [comment]
Done: https://github.com/flathub/com.github.philip_scott.spice-up/issues/3
