### ISSUE TITLE
GNOME does not recognize *.spice files in Nautilus

### ISSUE THREAD

**Issue by rugk** [Philip-Scott/Spice-up#178]
I don't know if that is supposed to work, but when opening `.spice` files from the file system via Nautilus, it only allows me to open it with a browser, not via the Spice-up application.

installed from Flathub
GNOME v3.26
Fedora 27

**Comment by Philip-Scott** [comment]
I'm really tempted to mark the issues with Flathub as invalid since flathub is not installing the files that make the mime as openable with Spice-Up, and not a problem with Spice-Up itself

You should files those issues here :) https://github.com/flathub/com.github.philip_scott.spice-up

**Comment by rugk** [comment]
Done: https://github.com/flathub/com.github.philip_scott.spice-up/issues/2
