### ISSUE TITLE
Packaging for PPA: Use git import on launchpad than bzr

### ISSUE THREAD

**Issue by khurshid-alam** [Philip-Scott/Spice-up#179]
Hi,

Launchpad can import code into git and you can create daily build recipes from it. Since launchpad doesn't support gpg signature in bzr import, git import would be a better choice. 

https://help.launchpad.net/Code/Git

If you need help ask me anything. Thanks.

**Comment by Philip-Scott** [comment]
Thank you! Just fixed it on launchpad :)
