### ISSUE TITLE
don't override the system-provided CFLAGS

### ISSUE THREAD

**Issue by decathorpe** [Philip-Scott/Spice-up#185]
At <https://github.com/Philip-Scott/Spice-up/blob/master/CMakeLists.txt#L18>, , you are overriding all system-provided CFLAGS with the `-ggdb` flag only. This breaks builds in some environments and builds the program with "insecure" build flags (no PIE, etc.).
Please drop this line entirely, or replace it with `set (CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -ggdb")` if the `-ggdb` flag is really necessary.

**Comment by Philip-Scott** [comment]
Fixed in 4ff30b6 :) Thanks for bringing it up!
