### ISSUE TITLE
Aspect ratio

### ISSUE THREAD

**Issue by wout** [Philip-Scott/Spice-up#197]
I love Spice-up for its simplicity but one feature I find missing is the ability to define a canvas size or the aspect ratio. I have a screen with unconventional dimensions and a presentation with two black bars does not look very nice.

Another solution might be to choose a fill colour for the uncovered area, but then it should be possible to define it for each slide in case different background colours are used between slides.

**Comment by Philip-Scott** [comment]
Sorry for not answering sooner, (i could've sworn i did) Spice-Up automatically takes your screen aspect-ratio into account when creating a new presentation. 

If the one that picked up for you is not the one you will be presenting at, you can click on the Gear icon when hovering over the presentations list on the welcome screen, and a menu will apear where you can change it :)

**Comment by wout** [comment]
Thanks Philip -Scott, I just noticed the gear/menu on the presentations. I'm using Pop!_OS and the gear is a white hamburger menu which is invisible against the white background of all presentations (I use white primarily :). So I didn't notice it at first.

**Comment by Philip-Scott** [comment]
Hmmm interesting, I might be able to make that better by making the icon white and adding a black drop shadow underneath the icon. Mind taking a screenshot of how it looks? :)

**Comment by Philip-Scott** [comment]
I've added a shadow on the icon. It now stand out on any background :) 

### Before
![image](https://user-images.githubusercontent.com/10786508/38783248-4416af10-40c5-11e8-967a-b3b5ad6cc0ea.png)

### Now
![image](https://user-images.githubusercontent.com/10786508/38783238-2cc38112-40c5-11e8-9098-3ba64c0dd8ad.png)
