### ISSUE TITLE
Save & Load Files

### ISSUE THREAD

**Issue by Philip-Scott** [Philip-Scott/Spice-up#2]
Because saving your work is important in these types of apps :wink: 

- [x] Serialize everything
- [x] Output to a file
- [x] Open a file on startup

**Comment by laberba** [comment]
Which file format(ppt, etc.) will you be using by default?

**Comment by Philip-Scott** [comment]
It's currently a json file, but i'm thinking of adding support for .odp later on as well as a way to export to pdf

The app most likely won't have all the features ppt and odp have available, so i think this is a good compromise

**Comment by laberba** [comment]
Maybe creating your own custom format will be convenient and will not restrict you.
