### ISSUE TITLE
hellp!!!!

### ISSUE THREAD

**Issue by slava8686** [Philip-Scott/Spice-up#205]
error: The type name `Granite.Widgets.Toast' could not be found
DEBUG:     private unowned Granite.Widgets.Toast? toast = null;
DEBUG:             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
DEBUG: /builddir/build/BUILD/Spice-up-1.3.2/src/Window.vala:355.41-355.61: error: The type name `Granite.Widgets.Toast' could not be found
DEBUG:     public void add_toast_notification (Granite.Widgets.Toast toast) {
DEBUG:                                         ^^^^^^^^^^^^^^^^^^^^^
DEBUG: /builddir/build/BUILD/Spice-up-1.3.2/src/Services/GamepadSlideController.vala:32.13-32.33: error: The type name `Granite.Widgets.Toast' could not be found
DEBUG:     private Granite.Widgets.Toast? toast = null;
DEBUG:             ^^^^^^^^^^^^^^^^^^^^^
DEBUG: Compilation failed: 3 error(s), 0 warning(s)
DEBUG: make[2]: *** [src/CMakeFiles/com.github.philip-scott.spice-up.dir/build.make:113: src/Main.c] Error 1
DEBUG: make[2]: Leaving directory '/builddir/build/BUILD/Spice-up-1.3.2/build'
DEBUG: make[1]: *** [CMakeFiles/Makefile2:214: src/CMakeFiles/com.github.philip-scott.spice-up.dir/all] Error 2
DEBUG: make[1]: Leaving directory '/builddir/build/BUILD/Spice-up-1.3.2/build'
DEBUG: make: *** [Makefile:142: all] Error 2

rosa linux

**Comment by Philip-Scott** [comment]
Looks like you have an older version of Granite, the elementary widget's library :) 

If you REALLY want to compile it, try to download https://github.com/elementary/granite/ and compile it on your system. After that you should be able to install it :)
