### ISSUE TITLE
Fonts changes not working

### ISSUE THREAD

**Issue by btd1337** [Philip-Scott/Spice-up#210]
Changes in the font as color, size and family, aren't reflecting in the text-box

**elementary version**: Juno Beta

![captura de tela de 2018-06-03 18-43-34](https://user-images.githubusercontent.com/11943860/40891565-213fa7e8-675e-11e8-8525-6e1ec95ec352.png)

**Comment by Philip-Scott** [comment]
How did you install it? Spice-Up is currently not officialy available on Juno and must be compiled from source for it to work on Juno (GTK 3.22+)

**Comment by btd1337** [comment]
Installation via Appcenter.

**Comment by Philip-Scott** [comment]
Yup, you probably added the Xenial (Loki) appcenter repo to your Juno install. It won't work and you either need to compile Spice-Up by yourself or wait until the Juno beta is officially out :)
