### ISSUE TITLE
Crash when rapidly moving slide

### ISSUE THREAD

**Issue by cassidyjames** [Philip-Scott/Spice-up#224]
I got my first and only crash so far! In my big presentation, I spammed the move down button to take a slide all the way to the end of the presentation, and I think I kept mashing when it got to the end, which caused Spice-Up to crash and lose some of my work.

**Comment by Philip-Scott** [comment]
Mmmmmm were you in the presenting mode? And were you smashing your Joy-Con or the keyboard?

**Comment by cassidyjames** [comment]
@Philip-Scott editing, moving the slide down the stack using the button in the toolbar.

**Comment by Philip-Scott** [comment]
Oh snap! Confirmed. Most likely an index out of bounds error

**Comment by Philip-Scott** [comment]
Fixed in 00308b6baf1ca795a284b100e803c92666e9905b :) Thanks for the bug report Cassidy!
