### ISSUE TITLE
Slides don't render until I click the item in the sidebar

### ISSUE THREAD

**Issue by danrabbit** [Philip-Scott/Spice-up#23]
When re-opening my presentation, nothing renders until I click in the sidebar

**Comment by Philip-Scott** [comment]
Yeah :disappointed: Sadly with the current method of rendering the preview, the slide has to be visible for it to create the image.... (The rendering is being triggered on click atm on purpose while i figure it out) 

I'll most likely have to store a cache of the preview

**Comment by donadigo** [comment]
Hm, these previews should be generated independent of whenever the slide is visible or not. So you should figure out a way to basically just draw them how normal slides but scale them down to the right size.

**Comment by Philip-Scott** [comment]
@donadigo I only have two problems with that though. 

Gtk is giving me problems when i scale it down a lot (Probably rounding errors) and causes inconsistencies. And I really don't want to have to load and render everything twice, specially when it comes to images
