### ISSUE TITLE
Update OARS data

### ISSUE THREAD

**Issue by cassidyjames** [Philip-Scott/Spice-up#234]
Since your app hits an online API, its `social-info` content attribute should be set to mild or higher:

```xml
<content_attribute id="social-info">mild</content_attribute>
```

If more diagnostic data is shared (i.e. more than a ping), it should be moderate or higher:

```xml
<content_attribute id="social-info">moderate</content_attribute>
```

If potentially user-identifiable data (like logs or usernames) are shared, it should be intense:

```xml
<content_attribute id="social-info">intense</content_attribute>
```

**Comment by Philip-Scott** [comment]
Set it to mild :) Thanks!
