### ISSUE TITLE
Ubuntu 18.04 dependency error

### ISSUE THREAD

**Issue by DanielRios549** [Philip-Scott/Spice-up#240]
I tried to install the deb version on Mint 19, but there is a dependency error, the program needs libgranite5, but the 18.04 repository has libgranite4. I think this happen with all Ubuntu 18.04 flavors and systems based on it.

![image](https://user-images.githubusercontent.com/11152535/46981427-a5d6ba00-d0ae-11e8-8dba-8bbad143a14c.png)

**Comment by Philip-Scott** [comment]
mmmm if you run updates, add the elementary stable PPA, and try to run updates again, does it try to replace anything? Sadly, Spice-Up requires that library.... you could try compiling it from source, but you'd also need to compile Granite. There's also a flatpak someone packaged, but it's currently a bit outdated

**Comment by DanielRios549** [comment]
I discover this program today, this the first time I tried to install it. Is it possible to use libgranite4 instead of libgranite5?

**Comment by DanielRios549** [comment]
Ok, I will test now, the package is already there. Additionally, you can change the name of this package, it can be only "spice-up" instead of "com.github.philip-scott.spice-up".

**Comment by Philip-Scott** [comment]
mmmmm actually,  the granite is not building yet. something failed. As of the package name, it's a requirement of AppCenter and thus not changeable :)

**Comment by DanielRios549** [comment]
Yes, it failed, Why don't you simply copy the package from ElementaryOS repository?

**Comment by Philip-Scott** [comment]
Can you just add any package? But i also want to make it so Granite auto-updates in case i later require newer versions :)

**Comment by DanielRios549** [comment]
I will search for them, but I think it is a good ideia fixing that, mainly because you want make it auto-update

**Comment by Philip-Scott** [comment]
No idea why it's failing but i figured out how to copy packages. Once it's published mind testing it out again? :)

Here's the status of the granite package: https://code.launchpad.net/~philip.scott/+archive/ubuntu/spice-up-daily/+packages (Might take a while for the package to propagate to your mirror)

**Comment by DanielRios549** [comment]
This package exists on Ubuntu 18.10 repository, and exists on pkgs.org as well, but the problem is that the version is 5.1.1, and it has a dependency of "libgranite-common", that is an older version on 18.04. It is said that the program needs "libgranite5" version 0.4.1 only, are you sure that you do not write "libgranite5" instead of "libgranite4"? I will try again right now.

**Comment by DanielRios549** [comment]
It was for install now, I am see that all dependencies are on PPA, but they are as "Pending" and not "Published"m and the package manager cannot see them

**Comment by DanielRios549** [comment]
About the package name, you can create another package call "spice-up", with no files, but "com.github.philip-scott.spice-up" package as a dependency, this is similar to meta packages, and it should solve this big name. But the important is that the program is now installing and working by the PPA, and i like it.

**Comment by Philip-Scott** [comment]
I actually don't mind the large name :) if everyone did it this way we could avoid collisions and that. I'll be closing the issue since you're able to install it now from the PPA
