### ISSUE TITLE
Syntax highlighting

### ISSUE THREAD

**Issue by ErikWallstrom** [Philip-Scott/Spice-up#243]
I would love to have a "insert code block" feature, where there is syntax highlighting etc. That would make this application really stand out for me.

**Comment by Philip-Scott** [comment]
Hopefully in the future once the new canvas tech is out you could have more than one text style on the same label, but for now you can "work around" this by taking a screenshot of your code, and pasting the image in the app from the clipboard :) that works from the latest version without having to add the image to a file first
