### ISSUE TITLE
Installation from ppa (ubuntu 18.04) breaks system font rendering

### ISSUE THREAD

**Issue by r1d1** [Philip-Scott/Spice-up#267]
Hi,
just wanted to try Spice-up on my 18.04 ubuntu machine, however, after installation, the system font are not rendered properly anymore:

Get:1 http://ppa.launchpad.net/philip.scott/spice-up-daily/ubuntu bionic/main amd64 libgranite-common all 5.2.3+r201902142146-1361+pkg107~ubuntu5.0.1 [71,1 kB]

Get:2 http://ppa.launchpad.net/philip.scott/spice-up-daily/ubuntu bionic/main amd64 libgranite5 amd64 5.2.3+r201902142146-1361+pkg107~ubuntu5.0.1 [155 kB]

Get:3 http://ppa.launchpad.net/philip.scott/spice-up-daily/ubuntu bionic/main amd64 com.github.philip-scott.spice-up amd64 0.2-1~3201903030614~ubuntu5.0.1 [1.028 kB]
![spiceup-pb1](https://user-images.githubusercontent.com/7498238/53727949-c773ea80-3e71-11e9-80a4-2fe5c2ebfae2.png)
![spiceup-pb2](https://user-images.githubusercontent.com/7498238/53727950-c80c8100-3e71-11e9-92a0-213f712ffbd1.png)

In-app text seems to be rendered correctly.

**Comment by r1d1** [comment]
Installed dependencies on my machine:

[spiceup-installedpkg.txt](https://github.com/Philip-Scott/Spice-up/files/2926006/spiceup-installedpkg.txt)

**Comment by Philip-Scott** [comment]
Did granite pull all those dependencies? I may just remove the PPA and just link to the flatpack if this is happening. Granite shouldn't cause anything else to install since it's a standalone library though

**Comment by r1d1** [comment]
I included the installedpkg text file for information (based on what's required for compiling the lib), but if the lib is standalone, then you can ignore this information :)

The combination of uninstalling spice up, libgranite-common and libgranite5 and logging out/in again solve the issue.
When apt-get install com.github.philipp-scott.spice-up,  the 2 libs are additionally installed.

I just reinstalled and the problem is gone now. Further manipulations with the interface (in particular going to presentation mode with 1/2 screens) don't break anything.
Might have been some weird issue happening at the same time I installed spice-up. Sorry for the inconvenience.
