### ISSUE TITLE
duplicate rule building from master

### ISSUE THREAD

**Issue by albfan** [Philip-Scott/Spice-up#270]
> ninja: error: build.ninja:1146: multiple rules generate src/Widgets/CanvasItems/Grabber.c [-w dupbuild=err]

I fixed with:

    ninja -C build -w dupbuild=warn

Just want to know the details about this (if I can help to solve it) Not an expert on meson by far.

**Comment by Philip-Scott** [comment]
Ninja? The project is currently being built with cmake, or are you trying to port it and getting those errors there?

**Comment by albfan** [comment]
nah, just an old setup to build from git in AUR:

https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=spice-up-git#n30

stable on AUR is better than bleeding edge:

https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=spice-up#n22
