### ISSUE TITLE
Web viewer seemingly unresponsive - possibly broken

### ISSUE THREAD

**Issue by edo0** [Philip-Scott/Spice-up#271]
After selecting the local .spice file to launch, no response comes from the website.
I reproduced the same behaviour in Brave (Chromium-based), Firefox and Epiphany, disabling any sort of ad-blocking extension.

**Comment by Philip-Scott** [comment]
Can you share the .spice file you're trying to open?

**Comment by edo0** [comment]
[This](https://www.brogiolo.eu/nextcloud/s/5C3T56jc5RCE6bP) is the file I have tried to open.
Monitoring resources, it seems not to even start uploading the file.
I am running openjdk version "1.8.0_191", and using Elementary OS Juno 5.0

**Comment by edo0** [comment]
Additional info. My console give a warning and an error on the webpage, the error showing up after I try to upload the presentation

![Screenshot from 2019-04-18 09 27 53](https://user-images.githubusercontent.com/16632292/56343972-8edb6680-61bc-11e9-9026-25e94939c5ff.png)

**Comment by edo0** [comment]
Furthermore, in spite of the certificate being marked as valid, my https connection is markes as non-secure
![Screenshot from 2019-04-18 09 30 48](https://user-images.githubusercontent.com/16632292/56346970-8f2b3000-61c3-11e9-98c5-3a95ac9c8a78.png)

**Comment by Philip-Scott** [comment]
Ahhh, i know what you're doing. I'm going to deprecate the site now, the web renderer is now included inside the file for quite a few versions 

Try opening the file directly in the web browser, if the browser tries to "download it", rename it as `.html`

**Comment by Philip-Scott** [comment]
Here's the webviewer working: 

![image](https://user-images.githubusercontent.com/10786508/56372686-175e0500-61c5-11e9-89bc-aa6e81ce4ebc.png)

**Comment by edo0** [comment]
Fantastic!
Thank you for the clarification.
