### ISSUE TITLE
Switch to the meson build system

### ISSUE THREAD

**Issue by NathanBnm** [Philip-Scott/Spice-up#276]
I think you should switch from cmake to meson. I can work on it if you want.

**Comment by Philip-Scott** [comment]
I'm not 100% sure atm, but iirc switching build systems is not as easy as just removing cmake and adding meson. I think it will also require packaging changes in Launchpad, for AppCenter, flatpak and wherever else is been used 😬

I'm waiting to merge your branch in Notes-Up for one day that I have free to be able to see what the consequences of changing it are, as well as being able to be there for the fallout if something happens :)

(also, do you know Why we should change the build systems? What could meson do that cmake does not? :) I'm curious as well about it, but I need to do further reading)

**Comment by NathanBnm** [comment]
Yes that's true.

Hmm yes, I'll be there if you have some issues with it. Just notify me :wink:

I talked about it with another developer but he wasn't convinced. You can take a look here: https://github.com/needle-and-thread/vocal/issues/386 and then make your own opinion about it.

You can read this article for further info: https://medium.com/elementaryos/all-aboard-the-meson-future-hype-train-2b6c478b6b9e

I we can invite @cassidyjames @donadigo or maybe @ryonakano to discuss about it. I need more clarity too I think. I'm not sure about the arguments.

@nathandyer you can debate too about it as we discussed it.

**Comment by danrabbit** [comment]
Fixed in #308!
