### ISSUE TITLE
Missing dependencies when trying to build from source on Ubuntu 19.04

### ISSUE THREAD

**Issue by wheresvic** [Philip-Scott/Spice-up#278]
## Expected Behavior
should build the app

## Current Behavior
Not sure what I am missing but cmake lists the following:
```
--   No package 'granite' found
--   No package 'gee-0.8' found
--   No package 'gudev-1.0' found
```
and unfortunately `sudo apt-get install granite` does not find anything :(.

## Your Environment (for bugs)
Running on ubuntu 19.04, if you could provide a list of dependencies that need to be installed, that would be amazing.

**Comment by ryonakano** [comment]
You need to run:

```
sudo apt install libgranite-dev libgee-0.8-dev libgudev-1.0-dev
```

**Comment by wheresvic** [comment]
Thanks for the tip, on ubuntu 19.04 libgranite is still at 5.2.2 but I managed to install the latest version manually and get it to build.

However, I am now getting the following error:

```
(Spice-Up:18088): GLib-GIO-ERROR **: 07:20:08.452: Settings schema 'com.github.philip-scott.spice-up' is not installed
Trace/breakpoint trap (core dumped)
```

Any ideas?

**Comment by Philip-Scott** [comment]
You need to install the app for it to run since it requires its settings :)

Try: `sudo make install`

**Comment by wheresvic** [comment]
Thanks for the tip! I actually managed to install the schema manually and it is working now:

```
sudo cp ./schemas/com.github.philip-scott.spice-up.gschema.xml /usr/share/glib-2.0/schemas/
sudo glib-compile-schemas /usr/share/glib-2.0/schemas/
gsettings list-schemas | grep com.github
```

I've updated the instructions for building on Ubuntu, I could make a PR if you'd like :)
