### ISSUE TITLE
Elementary Office proposal

### ISSUE THREAD

**Issue by PlatonB** [Philip-Scott/Spice-up#279]
I suggest to combine Spice-up, Spreadsheet and Writer into a single project with a common repository. It can be called something like Elementary Office. It's gonna be office suite that will become a minimalistic alternative to giant solutions like LibreOffice. @Philip-Scott @ryonakano

**Comment by esodan** [comment]
This is not a good idea for now. I think all projects should keep its repositories. But an Elementary Office repo can be created to: build all components using Meson subprojects, create distribution install packages like flatpak ones and maybe provide common libraries to be used along all subprojects.
