### ISSUE TITLE
icons used for 'bring forward' and 'send back'?

### ISSUE THREAD

**Issue by lxle** [Philip-Scott/Spice-up#287]
What icons and or their names are being called for the 'bring forward' and 'send back' buttons in Spice Up? I'm currently using an icon pack that doesn't support/have them so they are missing and I would like to add/address it so something appears for those buttons.  thanks.

**Comment by Philip-Scott** [comment]
They are called "selection-raise-symbolic" and "selection-lower-symbolic" :) Both icons are being set here: https://github.com/Philip-Scott/Spice-up/blob/master/src/Widgets/Toolbars/CommonBar.vala#L55
