### ISSUE TITLE
Build: abstract class cannot be public

### ISSUE THREAD

**Issue by genofire** [Philip-Scott/Spice-up#292]
```
-- The C compiler identification is GNU 9.2.1
-- The CXX compiler identification is GNU 9.2.1
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found PkgConfig: /usr/bin/pkg-config (found version "1.6.3")
-- Checking for modules 'granite>=5.2.3;gee-0.8;gtk+-3.0>=3.22.0;json-glib-1.0;gudev-1.0;libevdev;libsoup-2.4'
--   Found granite, version 5.3.0
--   Found gee-0.8, version 0.20.3
--   Found gtk+-3.0, version 3.24.13
--   Found json-glib-1.0, version 1.4.4
--   Found gudev-1.0, version 233
--   Found libevdev, version 1.8.0
--   Found libsoup-2.4, version 2.68.3
-- Found Vala: /usr/bin/valac
-- checking for a minimum Vala version of 0.26.0
--   found Vala, version 0.46.6
-- GSettings schemas will be installed locally.
-- GSettings shemas will be compiled.
-- GSettings schemas will be installed into /usr/share/glib-2.0/schemas/
-- Adding tests for genofire
-- Configuring done
-- Generating done
-- Build files have been written to: /home/genofire/.cache/yay/spice-up-git/src/Spice-up/build
make[1]: Entering directory '/home/genofire/.cache/yay/spice-up-git/src/Spice-up/build'
make[2]: Entering directory '/home/genofire/.cache/yay/spice-up-git/src/Spice-up/build'
Scanning dependencies of target i18n
make[2]: Leaving directory '/home/genofire/.cache/yay/spice-up-git/src/Spice-up/build'
make[2]: Entering directory '/home/genofire/.cache/yay/spice-up-git/src/Spice-up/build'
make[2]: Leaving directory '/home/genofire/.cache/yay/spice-up-git/src/Spice-up/build'
[  0%] Built target i18n
make[2]: Entering directory '/home/genofire/.cache/yay/spice-up-git/src/Spice-up/build'
[  1%] Generating ../data/assets.gresource.c
[  2%] Generating Main.c, Application.c, Window.c, Services/Clipboard.c, Services/Settings.c, Services/Slide.c, Services/SlideManager.c, Services/FileManager.c, Services/HistoryManager.c, Services/ImageHandler.c, Services/Utils.c, Services/GamepadSlideController.c, Widgets/Canvas.c, Widgets/EntryCombo.c, Widgets/Headerbar.c, Widgets/SlideList.c, Widgets/DynamicToolbar.c, Widgets/Welcome.c, Widgets/SlideWidget.c, Widgets/PresenterView.c, Widgets/PresenterNotes.c, Widgets/ColorPicker/ColorButton.c, Widgets/ColorPicker/ColorChooser.c, Widgets/ColorPicker/Gradient.c, Widgets/ColorPicker/GradientEditor.c, Widgets/ColorPicker/PickerWindow.c, Widgets/CanvasItems/CanvasItem.c, Widgets/CanvasItems/TextItem.c, Widgets/CanvasItems/ColorItem.c, Widgets/CanvasItems/ImageItem.c, Widgets/CanvasItems/Grabber.c, Widgets/Toolbars/CanvasBar.c, Widgets/Toolbars/CommonBar.c, Widgets/Toolbars/ImageBar.c, Widgets/Toolbars/ShapeBar.c, Widgets/Toolbars/TextBar.c, Widgets/Toolbars/Toolbar.c, Widgets/Library/LibraryItem.c, Widgets/Library/Library.c, Services/libgamepad/libgamepad.c, Services/libgamepad/gamepad-monitor.c, Services/libgamepad/gamepad.c, Services/libgamepad/helpers.c, Services/libgamepad/input-type.c, Services/libgamepad/raw-gamepad-interface.c, Services/libgamepad/raw-gamepad-monitor-interface.c, Services/libgamepad/standard-gamepad-axis.c, Services/libgamepad/standard-gamepad-button.c, Services/libgamepad/drivers/linux/guid-helpers.c, Services/libgamepad/drivers/linux/raw-gamepad.c, Services/libgamepad/drivers/linux/raw-gamepad-monitor.c, GraniteStaging/Inhibitor.c
Command-line option `--thread` is deprecated and will be ignored
/home/genofire/.cache/yay/spice-up-git/src/Spice-up/src/Widgets/CanvasItems/CanvasItem.vala:89.5-89.21: error: Creation method of abstract class cannot be public.
    public CanvasItem (Spice.Canvas? _canvas, Json.Object _save_data) {
    ^^^^^^^^^^^^^^^^^
Compilation failed: 1 error(s), 0 warning(s)
make[2]: *** [src/CMakeFiles/com.github.philip-scott.spice-up.dir/build.make:113: src/Main.c] Error 1
make[2]: Leaving directory '/home/genofire/.cache/yay/spice-up-git/src/Spice-up/build'
make[1]: *** [CMakeFiles/Makefile2:333: src/CMakeFiles/com.github.philip-scott.spice-up.dir/all] Error 2
make[1]: Leaving directory '/home/genofire/.cache/yay/spice-up-git/src/Spice-up/build'
make: *** [Makefile:141: all] Error 2
```

**Comment by worldofpeace** [comment]
Fixed in https://github.com/Philip-Scott/Spice-up/pull/288

**Comment by genofire** [comment]
got another build error:
```
src/Tests/ColorItem/MockedCanvasItem.vala:9.5-9.21: error: Creation method of abstract class cannot be public.
    public CanvasItem (Canvas canvas, Json.Object save_data) {
    ^^^^^^^^^^^^^^^^^
Compilation failed: 1 error(s), 0 warning(s)
make[2]: *** [src/Tests/ColorItem/CMakeFiles/color-item.dir/build.make:65: src/Tests/ColorItem/ColorItemTest.c] Error 1
make[2]: Leaving directory '/home/genofire/.cache/yay/spice-up-git/src/Spice-up/build'
make[1]: *** [CMakeFiles/Makefile2:414: src/Tests/ColorItem/CMakeFiles/color-item.dir/all] Error 2
make[1]: Leaving directory '/home/genofire/.cache/yay/spice-up-git/src/Spice-up/build'
make: *** [Makefile:141: all] Error 2
==> ERROR: A failure occurred in build().
    Aborting...
```

**Comment by worldofpeace** [comment]
> got another build error:
> 
> ```
> src/Tests/ColorItem/MockedCanvasItem.vala:9.5-9.21: error: Creation method of abstract class cannot be public.
>     public CanvasItem (Canvas canvas, Json.Object save_data) {
>     ^^^^^^^^^^^^^^^^^
> Compilation failed: 1 error(s), 0 warning(s)
> make[2]: *** [src/Tests/ColorItem/CMakeFiles/color-item.dir/build.make:65: src/Tests/ColorItem/ColorItemTest.c] Error 1
> make[2]: Leaving directory '/home/genofire/.cache/yay/spice-up-git/src/Spice-up/build'
> make[1]: *** [CMakeFiles/Makefile2:414: src/Tests/ColorItem/CMakeFiles/color-item.dir/all] Error 2
> make[1]: Leaving directory '/home/genofire/.cache/yay/spice-up-git/src/Spice-up/build'
> make: *** [Makefile:141: all] Error 2
> ==> ERROR: A failure occurred in build().
>     Aborting...
> ```

Ahh, I don't think I was building with tests to catch those.
Will add them to the patch.

**Comment by pete-m** [comment]
Hello there,
I'm trying to build Spice-Up... 
My Valac is 0.48


Getting a similar error message . . .
home/pete/git_repo/Spice-up/src/Widgets/CanvasItems/CanvasItem.vala:89.5-89.21: error: Creation method of abstract class cannot be public.

Any help would be much appreciated.


all the output . .
pete@debian-placid:~/git_repo/Spice-up/build$ make && sudo make all test install
/usr/local/bin/cmake -S/home/pete/git_repo/Spice-up -B/home/pete/git_repo/Spice-up/build --check-build-system CMakeFiles/Makefile.cmake 0
/usr/local/bin/cmake -E cmake_progress_start /home/pete/git_repo/Spice-up/build/CMakeFiles /home/pete/git_repo/Spice-up/build//CMakeFiles/progress.marks
make -s -f CMakeFiles/Makefile2 all
[  0%] Built target i18n
[  1%] Generating Main.c, Application.c, Window.c, Services/Clipboard.c, Services/Settings.c, Services/Slide.c, Services/SlideManager.c, Services/FileManager.c, Services/HistoryManager.c, Services/ImageHandler.c, Services/Utils.c, Services/GamepadSlideController.c, Widgets/Canvas.c, Widgets/EntryCombo.c, Widgets/Headerbar.c, Widgets/SlideList.c, Widgets/DynamicToolbar.c, Widgets/Welcome.c, Widgets/SlideWidget.c, Widgets/PresenterView.c, Widgets/PresenterNotes.c, Widgets/ColorPicker/ColorButton.c, Widgets/ColorPicker/ColorChooser.c, Widgets/ColorPicker/Gradient.c, Widgets/ColorPicker/GradientEditor.c, Widgets/ColorPicker/PickerWindow.c, Widgets/CanvasItems/CanvasItem.c, Widgets/CanvasItems/TextItem.c, Widgets/CanvasItems/ColorItem.c, Widgets/CanvasItems/ImageItem.c, Widgets/CanvasItems/Grabber.c, Widgets/Toolbars/CanvasBar.c, Widgets/Toolbars/CommonBar.c, Widgets/Toolbars/ImageBar.c, Widgets/Toolbars/ShapeBar.c, Widgets/Toolbars/TextBar.c, Widgets/Toolbars/Toolbar.c, Widgets/Library/LibraryItem.c, Widgets/Library/Library.c, Services/libgamepad/libgamepad.c, Services/libgamepad/gamepad-monitor.c, Services/libgamepad/gamepad.c, Services/libgamepad/helpers.c, Services/libgamepad/input-type.c, Services/libgamepad/raw-gamepad-interface.c, Services/libgamepad/raw-gamepad-monitor-interface.c, Services/libgamepad/standard-gamepad-axis.c, Services/libgamepad/standard-gamepad-button.c, Services/libgamepad/drivers/linux/guid-helpers.c, Services/libgamepad/drivers/linux/raw-gamepad.c, Services/libgamepad/drivers/linux/raw-gamepad-monitor.c, GraniteStaging/Inhibitor.c
Command-line option `--thread` is deprecated and will be ignored
/home/pete/git_repo/Spice-up/src/Widgets/CanvasItems/CanvasItem.vala:89.5-89.21: error: Creation method of abstract class cannot be public.
    public CanvasItem (Spice.Canvas? _canvas, Json.Object _save_data) {
    ^^^^^^^^^^^^^^^^^
Compilation failed: 1 error(s), 0 warning(s)
make[2]: *** [src/CMakeFiles/com.github.philip-scott.spice-up.dir/build.make:133: src/Main.c] Error 1
make[1]: *** [CMakeFiles/Makefile2:353: src/CMakeFiles/com.github.philip-scott.spice-up.dir/all] Error 2
make: *** [Makefile:161: all] Error 2
pete@debian-placid:~/git_repo/Spice-up/build$

**Comment by Philip-Scott** [comment]
It's currently building on Valac 0.48.20 :) So I'm closing this. Feel free to re-open if anyone sill experiences this issue
