### ISSUE TITLE
WebViewer can not load spice files anymore

### ISSUE THREAD

**Issue by Kkeller83** [Philip-Scott/Spice-up#294]
I downloaded the old webviewer javascript code but I get this error when loading a spice file saved with the most recent version of spiceup: 

"“SyntaxError: Unexpected Token in JSON”

What needs to be fixed to get the webviewer going again? 

thanks!

**Comment by Philip-Scott** [comment]
Ahh that web viewer is now deprecated in favor of the new system. Try either opening the spice-up from a web browser, or if that doesn't work try renaming the file to .html :) it should load up without any external tools
