### ISSUE TITLE
Compilation Error

### ISSUE THREAD

**Issue by jaum20** [Philip-Scott/Spice-up#300]
## Expected Behavior

The program should compile

## Current Behavior

I have installed all the dependencies listed on the readme, but cmake complains about "VALA_EXECUTABLE". I installed valac and now its complaining about "MSGMFT_executable". I have installed gettext but still not working

## Possible Solution

Update the readme with all the necessary dependencies to compile the program

## Steps to Reproduce (for bugs)

1. Use a clean debian install
2. Install the libraries liste on the readme section
3. try to compile the program
4. Missing dependencies errors

## Context

I'm tryng to compile the program

## Your Environment (for bugs)

Dietpi (Debian) aarch 64

`cmake ..`

```
<!--- Also, to avoid tagging other issues or pull requests, please keep this info inside of the ``` tags, thank you! ->

- Spice-Up Version: <!-- From Release, or Commit if compiled from source -->
- OS Info:

```

**Comment by Philip-Scott** [comment]
It's currently building on Valac 0.48.20 :) So I'm closing this. Feel free to re-open if anyone sill experiences this issue, or try using the flatpak build steps
