### ISSUE TITLE
Unmet dependencies Ubuntu 16.04

### ISSUE THREAD

**Issue by kantsdog** [Philip-Scott/Spice-up#41]
Depends on libgranite3 (>= 0.2.0), according to `apt`

A quick DuckDuckGo suggests that this dependency is related to the Pantheon DE. Is this a dependency that will be eliminated to make the program portable to distros beyond Elementary?

Edit: I am trying to install from the PPA

**Comment by Philip-Scott** [comment]
I've had luck installing the app in Ubuntu GNOME by adding the elementary PPA, BUT it may or may not break your system as iirc Ubuntu 16.04 has a different version of GTK.

Worst case scenario, I might later include the widget classes I've used from Granite with the project, but you might still not get the best results if you are not running on elementary (or in a system with the same GTK Version at the very least)
