### ISSUE TITLE
Deleting slides

### ISSUE THREAD

**Issue by martykan** [Philip-Scott/Spice-up#55]
Can't currently delete slides, or at least I don't know how
EDIT: I found out how to move slides, but had to check the source code. The deleting of slides is broken for me.

**Comment by Philip-Scott** [comment]
To delete and move the slides, the slide needs to be the one selected (you need to have on the toolbar the slide options) I did find a bug where the canvas wasn't automatically selected if you deleted an item, is that the problem you found?

**Comment by xwing7** [comment]
I have the same problem that when i select one  and hit the delete button on the right nothing happens.
it doesn't delete it

**Comment by Philip-Scott** [comment]
There were quite a few changes to how slides and objects are deleted. I'm going to close it but feel free to re-open it if you can still confirm :)
