### ISSUE TITLE
Export functionality

### ISSUE THREAD

**Issue by JLIT0** [Philip-Scott/Spice-up#60]
I can't seem to find the ability to export (or import) using PDF, ODF or OOXML.

**Comment by JLIT0** [comment]
Strangely enough I can see the export to PDF button on Ubuntu MATE but not on Elementary.

**Comment by Philip-Scott** [comment]
Importing/exporting to other formats is something that has not being done atm..... With the ever changing file formats it would be too hard too keep up :( 

weird that you can't export on Elementary though, are you using Loki? Any themes? Also, do you get any errors on the terminal window? That would help narrow it down :)

**Comment by JLIT0** [comment]
I'm using Loki and the pre-compiled PPA.  No errors on launching from the terminal window.  

As you can see in the screenshot, I'm strangely not seeing the export button (although I was seeing it in MATE ).

![screenshot from 2017-02-09 14 45 43](https://cloud.githubusercontent.com/assets/24968860/22786038/36646736-eed7-11e6-9501-89622b8e7837.png)

Regarding other formats, I completely understand.  PDF is a good format for sharing presentations.
Perhaps an external library (e.g. LibreOfficeKit) might be able to external export in the future.

**Comment by Philip-Scott** [comment]
@JLIT0 Hey, i asked some question over at https://github.com/Philip-Scott/Spice-up/issues/62 about the app icon not showing up, mind answering them? :) 

Thanks

**Comment by JLIT0** [comment]
Thanks

**Comment by mikhailnov** [comment]
Can you please make wxport to HTML? Its a stable format, and SpiceUp can be a really nice application for quick creating of presentations for the web, which can be further iframed anywhere.

**Comment by Philip-Scott** [comment]
@mikhailnov You should be happy to know that I actually did decide to do something with web and HTML. 

PR #164 makes any presentation saved from now openable from a web browser! So there won't even be a need to "export" a presentation. It will just be openable from any web browser :smile:
