### ISSUE TITLE
Some locales break text formating

### ISSUE THREAD

**Issue by xwing7** [Philip-Scott/Spice-up#61]
when you select the text color to be black or red. it doesn't change.
even if you select the color first and then type the text.

**Comment by Philip-Scott** [comment]
I can't seem to be able to confirm your problem :/ 
Does the colors never change for you? Or is it only those colors?

**Comment by xwing7** [comment]
the color never changes it stays black

**Comment by Philip-Scott** [comment]
Seems to be a problem with the LOCALE. CSS expects numbers to be with decimal points, but on locales such as nl_NL numbers are separated with commas `0,3`. Forcing the locale within the app should fix it :)
