### ISSUE TITLE
No icon in slingshot

### ISSUE THREAD

**Issue by kvdz** [Philip-Scott/Spice-up#62]
slingshot shows default icon.  so i assume there is no icon yet?  or did the link break?

**Comment by Philip-Scott** [comment]
Are you using any icon theme? Did you build from source or installed it from the PPA? Can you confirm that the icon is on `/usr/share/icons/hicolor/scalable/apps/com.github.philip-scott.spice-up.svg`?

Thanks :)

**Comment by wecassidy** [comment]
I can confirm this (elementary OS 0.4 Loki, 64-bit). I installed using the PPA. `/usr/share/icons/hicolor/scalable/apps/com.github.philip-scott.spice-up.svg` doesn't exist. `find /usr/share/icons -name '*spice-up*'` doesn't turn anything up.

**Comment by JLIT0** [comment]
No such directory exists on my install either, strangely

**Comment by xwing7** [comment]
i also installed it on loki via  the ppa.

**Comment by alexgleason** [comment]
The .desktop file says `Icon=spice`, so shouldn't the file be called `spice.svg`? Either way, I'm having no luck manually copying in the icon either. Though I'm sure I'm doing something wrong.

**Comment by Philip-Scott** [comment]
With the recent changes to now use `com.github.philip-scott.spice-up` everywhere, i'm going to asume this is fixed now :D
