### ISSUE TITLE
Gtk-warnings when using newer GTK+3.x-versions

### ISSUE THREAD

**Issue by dominikfranz** [Philip-Scott/Spice-up#63]
Hi!
I am trying to compile Spice-up on Solus and it builds fine, however, when running it I get massive amounts of warnings and errors similar to this one:
```
(Presentations:15018): Gtk-WARNING **: Theme parsing error: <data>:3:31: Using Pango syntax for the font: style property is deprecated; please use CSS syntax

** (Presentations:15018): WARNING **: Utils.vala:59: Style error: <data>:3:18not a number
GtkLabel 
        .label {
            font: Lohit Kannada;
            font-size: 14px;
        }
```
and this one:
```
(Presentations:15461): Gtk-WARNING **: Allocating size to SpiceTextItem 0x27cdc50 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?
```
I've read that some apps seem to have this problem with newer versions of GTK+ 3 as well (Solus is currently on 3.22.7). It also seems it has some display issues (probably related to the issues above?), e.g. the corner dots to resize an element - see screenshot. Also text configuration options (font, font size, font weight) have no effect.
I would greatly appreciate any help! I love how Spice-up develops and think it has quite some potential - it would be great if we could have it on other distributions as well.

![spice-up error](https://cloud.githubusercontent.com/assets/816218/22868368/edd63810-f18c-11e6-9c3f-cd4c0a2e386f.png)

**Comment by Philip-Scott** [comment]
To be honest, i don't think i'll be messing with this atm. At least not UNTIL elementary jumps to start using a newer version of Gtk. The main reason is that Gtk3.22 has a different api for styling elements with CSS, so fixing it in one version would break it in another (And i really don't want to have to maintain 2 codebases)

One thing i will take from this report though is to fix the corner dots. Those should work regardless of what icon theme you're using :)
