### ISSUE TITLE
Text decoration does not work

### ISSUE THREAD

**Issue by JO0st** [Philip-Scott/Spice-up#68]
When inserting text the styling options do not work, and this message is shown in the terminal/
    

    (Presentations:11910): Gtk-WARNING **: Theme parsing error: <data>:6:25: Not using units is deprecated. Assuming 'px'.

    ** (Presentations:11910): WARNING **: Utils.vala:33: Style error: <data>:6:25Junk at end of value
    SpiceTextItem 
            .colored {
                color: #fff;

                font: open sans bold;
                font-size: 18,048000px;
                background: 0;
            }

**Comment by Philip-Scott** [comment]
Let me guess, your system is on a language where decimals are notated with a `,`? :wink: This should've been fixed on https://github.com/Philip-Scott/Spice-up/pull/67 though... Are you not on the newest version?

**Comment by JO0st** [comment]
I was running the latest version from the PPA. On compiling the github version everything worked. Thanks for your reply and fixing it.
