### ISSUE TITLE
HTML5 Framework backend

### ISSUE THREAD

**Issue by sschuhmann** [Philip-Scott/Spice-up#83]
It would be awesome to use a HTML5/Javacscript/CSS backend to store the presentations. This woul support using the presentations on other operating systems( through a browser ), could simplify the theming process and also would give the option to easily share the presentation online.

One of these frameworks I personally love to use is [reveal.js](http://lab.hakim.se/reveal-js/#/), but there might be many more

**Comment by Philip-Scott** [comment]
Marking this as `wont-fix` as i'm trying to do everything natively using only Gtk :)  It's mostly as a personal challenge to see how far i can take Gtk
